### ISSUE TITLE
emmet 설정 질문 입니다.

### ISSUE THREAD

**Issue by neofnd** [yamoo9/Making-Modern-Web-Design-Work-Process#2]
책 166페이지 다른이름으로 링크 저장을 눌러 다운을 받고 lorem-ko.js를 서브라임에서 열면 html 파일들이 들어가 있는 페이지로 열립니다.

그림3의 주석에 대한 내용은 없구요.
그래서 깃에서 복사를 해서 lorem-ko.js 코드를 동일하게 만들고 저장를 했는데도

p_2>lorem2 입력 후 탭을 눌러도 p태그만 두개 생성이 됩니다.
p_2>loremen2 입력 후 탭을 누르면 영어로는 잘 됩니다.

한글이 출력이 안되고 p태그만 생기는데요. 무엇이 문제인지 궁금합니다.

참고

lorem-ko.js
`
/*! yamoo9.net @ 2014 

  아래 코드를 복사해서 Emmet.sublime-settings - User 파일에 붙여넣습니다.

  "extensions_path": "c://emmet",
  "preferences": {
    "lorem.defaultLang": "ko"
  }
 */
emmet.require('generator/lorem').addLang('ko', '야무 한글 로렘입숨 더미텍스트 - 보기만 해도 찬란한 그대 젊음의 청춘 세상을 씩씩하게 만들 사명으로 하루를 엮어가는 너 청춘 피어나는 꽃처럼 눈부신 햇볕처럼 어디에나 빛나는 청춘아 가슴을 설레게 하고 장엄한 숨소리가 쿵쿵대는 청춘의 심장 고동소리 흐르는 땀 소리 숨죽여도 다 들리는 내일의 소리 티셔츠 운동화도 거추장스런 너 청춘 너야말로 꽃보다 아름답다 쉬지 않고 설레는 청춘아! 실수조차도 아름다운 너 청춘아!');
`

```
// Emmet 확장 경로 설정
"extensions_path": "c://emmet",

"preferences": {
    // Lorem Ipsum 기본 언어 설정: 한글(ko), 영어(en), 러시아어(ru)
    "lorem.defaultLang": "ko",

    // CSS Hex 컬러 단축(3 Dgit) 설정
    "css.color.short": false,

    // CSS 벤더 프리픽스 자동 추가 설정
    // "css.autoInsertVendorPrefixes": false,

    // CSS 그레디언트 대체 컬러 추가 설정
    "css.gradient.fallback": true,

    // CSS 그레디언트 구형 Webkit 문법 추가 설정
    // "css.gradient.oldWebkit": true,

    // 영역 시작/끝 지점에 코멘트 추가 설정
    "filter.commentBefore": "<!-- 시작: <%= attr('id', '#')%><%= attr('class', '.')%> -->\n",
    "filter.commentAfter": "\n<!-- 끝: <%= attr('id', '#')%><%= attr('class', '.')%> -->"
}
```

**Comment by neofnd** [comment]
참고로 윈도우10 프리뷰 버전 사용중 입니다.~

**Comment by yamoo9** [comment]
안녕하세요 neofnd님 ^ㅡ^ 야무입니다.

책 구매 독자 분들 중 처음으로 질문주셨네요! 정말 감사합니다!!
안그래도 Emmet 장을 읽으셨다면 이 문제 질문을 주셔야 하는데... 

그간 아무도 물어봐 주지 않아 살짝 서운(?) 했습니다. ^^;
이제야 질문을 주신 독자분이 계시니 서운함이 싹~ 가시네요 ㅎ

## 

사실... 책을 집필하던 당시만 하더라도 책에 기술한데로 하면 Emmet에서 
Lorem 입력시 한글 생성이 가능했습니다. 하지만... 책이 출간된 이후
어떤 문제에서인지... 이 방법을 사용할 수 없게 되었습니다.

이 문제에 대한 해결책을 Emmet 개발자 [Sergey Chikuyonok](https://github.com/sergeche)에게 문의했으나
답변을 안하더라고요. 아래 링크는 제가 질문했던 이슈에요. (지금도 답변이 없네요)

[Lorem Ipsum Generator Customize does not work.](https://github.com/sergeche/emmet-sublime/issues/529)

## 

그래서 이 문제를 해결할 방법이 없을까 고심하던 끝에 방법을 찾았답니다. :-)
이제 그 방법을 공유해드릴께요~! 따라하기 쉬우시라고 동영상으로 올렸습니다.
아래 링크를 클릭해서 동영상으로 방법을 확인해보세요 :-)

[(Youtube 동영상) Emmet 사용시, 한글 로렘입숨을 생성하는 방법은?](https://youtu.be/1nI9Uc0NZWY)

**Comment by neofnd** [comment]
감사합니다. 영상대로 app.js를 세팅 후 시도하니 잘 되네요 ㅎ 좋은책 써 주셔서 진심으로 감사드리며 하나 하나 다 해볼거에요~ ㅎ 안되면 계속.....여쭈어 볼겁니다....이 책으로 저의 목마름이 좀 가셨으면 좋겠어요. 맨날 하는 것만 하니......점점 흥미를 잃어 가는것 같아요,

**Comment by gjjoo** [comment]
맥이라서 안되는줄 알고 포기하고 넘어갔는데... 나중에 stackoverflow 찾아보다가 다행히 이 글을 찾아서 해결했네요~ 감사합니다!
