### ISSUE TITLE
또 질문 입니다. ㅠㅠ node 책 220 페이지

### ISSUE THREAD

**Issue by neofnd** [yamoo9/Making-Modern-Web-Design-Work-Process#3]
combine.js

``` js
var fs= require('fs');
/**
 * combineJS 모듈 정의 및 외부로 출력
 * 모듈 내부에 전달 받을 인자(배열, 문자열) 설정
 */

module.exports = function (jsSrc, exportJs) {
    //배열 jsSrc를 개별적으로 접근 조작하기 위해
    //forEach 배열 메소드 사용.
    jsSrc.forEach(function(file, index){
        var content = fs.readFileSync(file);
        console.log('콘텐츠 : \n', content);
    });
}
```

mergeScript.js

``` js
//사용자 정의 모듈 'modules/combineJS.js' 호출
var combineJS = require('./modules/combineJS.js');

//combineJS 모듈 사용
combineJS(['./readFile.js','./writeFile.js'],'./jsCombile.js');
```

이런식으로 하고 node 실행하면

콘탠츠 :

<Buffer 2f 2f 6e 64.......이런식으로 두개가 나오는데요. 원래 이렇게 출력되는것이 맞는건가요?
책에는 읽기 프로세스 시작... 부터 해서 쫘악 나오는데...

아무리 수정을 해도 책 처럼 안나와서 질문을 드려 봅니다.

**Comment by neofnd** [comment]
node 버전은 v0.12.4 라고 나옵니다.

**Comment by yamoo9** [comment]
안녕하세요  @neofnd 님~ ^ㅡ^ 질문주신 내용에 답변드립니다. 

`File System` 객체의 `readFileSync()` 메소드는 첫번째 전달인자로 `filename`을,
두번째 전달인자(선택)로 `encoding`을 전달할 수 있습니다. 두번째 전달인자를 
설정하지 않으면 `<Buffer>` 데이터를 반환하고, 설정하면 문자열 데이터를 반환합니다.

[사용법을 읽어보세요] Node.js API - [fs.readFileSync](http://nodejs.org/docs/v0.8.20/api/fs.html#fs_fs_readfilesync_filename_encoding)

``` js
// fs.readFileSync(filename, [encoding])
var content = fs.readFileSync('./answer.js', 'utf-8');
```

## 

`Git Bash` 창 화면에 버퍼 데이터가 아닌, 텍스트 데이터를 출력하고자 한다면
아래 코드처럼 `fs.readFileSync()`에 두번째 전달인자를 전달하면 됩니다. ^ㅡ^

``` js
// combine.js
var fs= require('fs');

module.exports = function (jsSrc, exportJs) {
    // 배열 jsSrc를 개별적으로 접근 조작하기 위해
    // forEach 배열 메소드 사용.
    jsSrc.forEach(function(file, index){
        // fs.readFileSync(파일경로, 언어인코딩) 
        var content = fs.readFileSync(file, 'utf-8');
        console.log('콘텐츠 : \n', content);
    });
}
```

**Comment by neofnd** [comment]
감사합니다. 해결 되었습니다.
