### ISSUE TITLE
215p "http-server" option 부분 질문입니다

### ISSUE THREAD

**Issue by gjjoo** [yamoo9/Making-Modern-Web-Design-Work-Process#4]
<img width="500" alt="http-server error" src="https://cloud.githubusercontent.com/assets/10864943/9320812/320d40b0-4599-11e5-8d3d-d442244601ff.png">

-p 옵션만 자꾸 에러가 나는데 왜그럴까요..ㅠ
제 컴퓨터만 그런건지;; 해결해볼려고 하는데 잘 안되네요..
운영체제는 MacOS 입니다.

**Comment by yamoo9** [comment]
수퍼 유저(관리자) `sudo` 권한으로 실행해보세요 :-)

``` java
$ sudo http-server -a localhost -p 80
```

![Issue #4](https://raw.githubusercontent.com/yamoo9/Making-Modern-Web-Design-Work-Process/master/Assets/issue-%234.png)

**Comment by gjjoo** [comment]
감사합니다! sudo 하니깐 되네요.. 사용자설정에서 관리자권한으로 해놔서 당연히 되는줄 알았습니다..
하긴 설치시에도 "npm install http-server -g"로 하면 에러가나서 sudo로 하긴 했는데 멍청하게..ㅠ
