### ISSUE TITLE
sass에서 emmet사용 질문입니다.

### ISSUE THREAD

**Issue by gjjoo** [yamoo9/Making-Modern-Web-Design-Work-Process#5]
emmet에 적응이되어 없이 못사는 실정입니다..
jade에서도 지원이 되는듯 한데, sass에서는 사용 못하는건가요??
책에는 따로 sass에서 emmet사용 관련 내용이 없네요...
네이버로는 나오지 않고 구글링 하자니 영어는 쥐약이라 ㅠㅠ
혹시 방법이 없을까요..

**Comment by gjjoo** [comment]
"Emmet Css Snippets" Package 깔아서 해결했네요..
글 닫도록 하겠씁니다 ㅠㅠ

**Comment by yamoo9** [comment]
Emmet Css Snippets를 설치하지 않으셔도 Sass 문서에서 Emmet 사용이 가능합니다. ^^

![Emmet Sass](https://raw.githubusercontent.com/yamoo9/Making-Modern-Web-Design-Work-Process/master/Assets/emmet-sass.gif)
